
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMENT TOKROOMSTART TOKROOMEND TOKOCCUPANCY TOKNICK TOKSVGID INT STRINGroom_set : room\n                | room_set roomroom : TOKROOMSTART STRING config_group TOKROOMENDconfig_group : config_phrase\n                    | config_group config_phraseconfig_phrase : TOKOCCUPANCY INT\n                     | TOKNICK STRING\n                     | TOKSVGID STRING'
    
_lr_action_items = {'TOKNICK':([4,9,10,11,12,13,15,],[6,6,-4,-7,-6,-8,-5,]),'TOKOCCUPANCY':([4,9,10,11,12,13,15,],[7,7,-4,-7,-6,-8,-5,]),'TOKSVGID':([4,9,10,11,12,13,15,],[8,8,-4,-7,-6,-8,-5,]),'TOKROOMEND':([9,10,11,12,13,15,],[14,-4,-7,-6,-8,-5,]),'INT':([7,],[12,]),'$end':([1,3,5,14,],[-1,0,-2,-3,]),'TOKROOMSTART':([0,1,3,5,14,],[2,-1,2,-2,-3,]),'STRING':([2,6,8,],[4,11,13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'config_phrase':([4,9,],[10,15,]),'room_set':([0,],[3,]),'room':([0,3,],[1,5,]),'config_group':([4,],[9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> room_set","S'",1,None,None,None),
  ('room_set -> room','room_set',1,'p_room_set','config_lexer.py',85),
  ('room_set -> room_set room','room_set',2,'p_room_set','config_lexer.py',86),
  ('room -> TOKROOMSTART STRING config_group TOKROOMEND','room',4,'p_room','config_lexer.py',95),
  ('config_group -> config_phrase','config_group',1,'p_config_group','config_lexer.py',103),
  ('config_group -> config_group config_phrase','config_group',2,'p_config_group','config_lexer.py',104),
  ('config_phrase -> TOKOCCUPANCY INT','config_phrase',2,'p_config_phrase','config_lexer.py',120),
  ('config_phrase -> TOKNICK STRING','config_phrase',2,'p_config_phrase','config_lexer.py',121),
  ('config_phrase -> TOKSVGID STRING','config_phrase',2,'p_config_phrase','config_lexer.py',122),
]
